name: Aiya
description: Find, create and join activities in your area.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  emojis: ^0.9.3 # vor emoji support
  #location: ^4.1.1 # location services
  #google_maps_flutter: ^2.0.3 # google maps
  google_fonts: ^2.0.0
  flutter_signin_button: ^2.0.0
  font_awesome_flutter: ^9.0.0
  flutter_launcher_icons: ^0.9.0 # for the launcher icon
  share_plus: ^2.0.1 # share functionality
  image_cropper: ^1.4.0 # crop images
  image_picker: ^0.7.4 # image picker #TODO: remove image picker and use file_picker instead
  cached_network_image: ^3.0.0
  getwidget: ^1.2.4 # widget library for UI
  #timeline_tile: ^2.0.0 # timeline ui
  animations: ^2.0.0 # page transition animations
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.5
  file_picker: ^3.0.1
  url_launcher: ^6.0.3 # for phonecall launch, whatsapp etc.
  #badges: ^1.2.0
  google_sign_in: ^4.5.1
  photo_view: ^0.11.1
  flutter_local_notifications: ^5.0.0+3
  #firebase_dynamic_links: ^2.0.2
  uni_links: ^0.5.1 # deeplinks
  #pull_to_refresh: ^2.0.0
  flutter_cache_manager: ^3.0.1






  # Firebase stuff
  cloud_firestore: ^1.0.6 # Firebase
  firebase_analytics: ^8.0.1 # firebase
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  firebase_storage: ^8.0.4
  path_provider: ^2.0.1 # needed for firebasestorage
  firebase_crashlytics: ^2.0.1
  firebase_messaging: ^9.1.2




  # helper stuff
  basic_utils: ^3.0.2 # helper functions for dart
  #pedantic: ^1.11.0 # static code analysis with google rules
  provider: ^5.0.0 # for multiprovider
  intl: ^0.17.0 # For DateTime
  supercharged: ^2.0.0 # for easier code writing

  #dart_style: ^1.3.12 # nicer dart code


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  # use flutter pub run flutter_launcher_icons:main

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
